### ISSUE TITLE
Add scrollbar to slider menus for some simulations

### ISSUE THREAD

**Issue by shreyamalviya** [yashlamba/simulate#104]
For some simulations, there are multiple sliders (adjustable parameters, example given in below screenshots), and some of those get hidden. Unless a completely new user accidentally stumbles across them, they won't know about them.

Maybe adding a scrollbar or something of that sort to indicate that there are more sliders to play around with, would help make it obvious.

<img src="https://user-images.githubusercontent.com/44770317/76532036-12203d80-649c-11ea-819a-a2fead4e208c.jpeg" height=400> <img src="https://user-images.githubusercontent.com/44770317/76532043-13516a80-649c-11ea-9f8d-3dc88fea0430.jpeg" height=400>

**Comment by yashlamba** [comment]
I agree, it will be great to have something to make scrolling obvious. Continuation of #72.

**Comment by payal-98** [comment]
can I try this?

**Comment by shreyamalviya** [comment]
@payal-98, sure, go ahead. Let us know if you need any help. All the best!

**Comment by payal-98** [comment]
I added the scollbar..

**Comment by payal-98** [comment]
I made a PR...Please review it @shreyamalviya

**Comment by Rishika1416** [comment]
we are a team of developers ,we would like to work upon this issue #104 .can we proceed?

**Comment by yashlamba** [comment]
Closed via #140
