### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Aman-Codes** [yashlamba/simulate#108]
**Is your feature request related to a problem? Please describe.**
No CODE_OF_CONDUCT.md file is present.

**Describe the solution you'd like**
@yashlamba   As a GSSOC participant I would like to add a CODE_OF_CONDUCT.md file in this project. Using [this]( https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) as a reference. 

**Additional context**
### Screenshots

![code of conduct1](https://user-images.githubusercontent.com/54680709/77505634-beddc000-6e89-11ea-9dd5-f1e13ef6c6c9.PNG)
![code of conduct2](https://user-images.githubusercontent.com/54680709/77505638-c0a78380-6e89-11ea-8aa4-efcb21133da7.PNG)

**Comment by yashlamba** [comment]
This is administrative doc and I don't think we need it now in simulate.

**Comment by Aman-Codes** [comment]
Ok sir
