### ISSUE TITLE
Add Data Structures Visualization to this project

### ISSUE THREAD

**Issue by SamarpanCoder2002** [yashlamba/simulate#158]
**Data Structure Visualization**
Hello, I would like to add some data structure visualizer(like the stack, queue, link list) in this project.. I already worked on it in python Tkinter(You can check it out on my account), but I have knowledge of how to implement it in flutter... Can I go forward with this? I am also a **_gssoc'21_** participant....... If you give permission to forward with my ideas.... Please assign me to here.... Thanks, @coded-org .....

**Data Structure Visualization** [Data Structure]

**My GitHub account: https://github.com/SamarpanCoder2002**

**Comment by yashlamba** [comment]
@SamarpanCoder2002  Go ahead! Please share the branch on gitter once you implement the basic structure. Refrain from opening a PR until you are done.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 Go ahead! Please share the branch on gitter once you implement the basic structure. Refrain from opening a PR until you are done.

Ok I will make it as soon as possible and will send a PR...... By the way, I am also a **_GSSOC'21_** participant....Please add the labels **_gssoc'21_** ....  Thanks

**Comment by yashlamba** [comment]
@SamarpanCoder2002 , As I mentioned, don't open a PR until you share the branch on discord or gitter.

@yashugarg Let's keep this a tracker issue for DS simulations and open other issue linked to this for various DS.

**Comment by yashlamba** [comment]
C
