### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [yashlamba/simulate#159]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by yashlamba** [comment]
@rohank2502 It would be better if you tell us your approach first! I'd love to hear it.

Another thing, don't add a contributors section in the readme, rather in the docs. We use mkdocs to simulate, you can learn more about it here: https://www.mkdocs.org/

I'll mark this with the appropriate labels once you let us know the approach!

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> @rohank2502 It would be better if you tell us your approach first! I'd love to hear it.
> 
> Another thing, don't add a contributors section in the readme, rather in the docs. We use mkdocs to simulate, you can learn more about it here: https://www.mkdocs.org/
> 
> I'll mark this with the appropriate labels once you let us know the approach!

Ok no issues But I have to learn this type of docs to make my contribution and I am going to attach a img tag ! Does this doc support adding tags ? IF yes then we can go for it !

**Comment by sahilempire** [comment]
I want to work on this issue as a GSSoC participant, please assign me.

Thank you.
