### ISSUE TITLE
simulations: bubble_sort: Moving slider after simulation is complete results in unusual behaviour

### ISSUE THREAD

**Issue by apoorvdwi** [yashlamba/simulate#161]
**Describe the bug**
When the bubble sort simulation is complete and green color is being highlighted on all bars, if the elements slider is moved it results in unusual behaviour with elements being reinitialised and sorted stuck in infinite loop.

**To Reproduce**
1. Open the bubble sort simulation
2. Run the simulation for desired number of elements
3. When the green color is highlighting all the bars after the sorting is done, move the elements slider

**Expected behavior**
A new set of random elements should be created and the simulation should not enter into infinite loop

**Screenshots**
![bubble sort simulation bug](https://user-images.githubusercontent.com/56197821/112167494-809eec00-8c16-11eb-8329-ecf0586ff6e9.gif)

**Comment by apoorvdwi** [comment]
I am a gssoc participant and I would like to work on this issue please assign this issue to me and add gssoc label as well

**Comment by yashugarg** [comment]
@apoorvdwi please go ahead and discuss on the discord channel if you face any issues
