### ISSUE TITLE
simulation: Selection Sort

### ISSUE THREAD

**Issue by yashugarg** [yashlamba/simulate#162]
**Selection Sort**
[https://en.wikipedia.org/wiki/Selection_sort](https://en.wikipedia.org/wiki/Selection_sort
)

**Category Proposed:** Algorithms

**Additional points/links:**
[https://www.geeksforgeeks.org/selection-sort/](https://www.geeksforgeeks.org/selection-sort/)

**Comment by apoorvdwi** [comment]
I am a gssoc participant, I would like to work on this issue please assign this to me

**Comment by yashugarg** [comment]
@apoorvdwi go ahead and start working! you can contact us on gitter and discord in case you face any issues.
