### ISSUE TITLE
simulation: Hypocycloid Curve

### ISSUE THREAD

**Issue by yashugarg** [yashlamba/simulate#164]
**Hypocycloid Curve**
[https://en.m.wikipedia.org/wiki/Hypocycloid](https://en.m.wikipedia.org/wiki/Hypocycloid)

**Category Proposed:** Mathematics

**Additional points/links:**
![https://upload.wikimedia.org/wikipedia/commons/1/1b/Astroid2.gif](https://upload.wikimedia.org/wikipedia/commons/1/1b/Astroid2.gif)

**Comment by subhasmitapradhan** [comment]
I would love to work on this but first may I know which software do you prefer?

**Comment by Snehaa1203** [comment]
I am a GSSOC'21 member I would like to work on this issue.
