### ISSUE TITLE
simulation: Pigeonhole sort

### ISSUE THREAD

**Issue by mrmayurgithub** [yashlamba/simulate#166]
**Pigeonhole sort**
https://en.wikipedia.org/wiki/Pigeonhole_sort

**Category Proposed:**  Algorithms

**Additional points/links:**
https://www.geeksforgeeks.org/pigeonhole-sort/

I am a **gssoc21** participant and I want to add a simulation of pigeonhole sorting algorithm.

**Comment by yashugarg** [comment]
Sure @mrmayurgithub please go ahead!
