### ISSUE TITLE
Modifying/Styling Readme.md file. 

### ISSUE THREAD

**Issue by DOOMSTERR** [yashlamba/simulate#168]
## Request ✨
Hello sir, I want to modify the readme.md file.

### Modifying it by adding 

1.)Adding shield batches in different colors for(at center-top below simulate image):
-> issues-open
-> pull_request-open
-> total no. of forks
-> total no. of stars

2.) Sections
->Feature Section
->Dependencies Section
->Contributors Section
->Project Manager/Admin Section
->Changing Contributing section to Contributing Guidelines Section 

3.) Also, Should I add a section for steps to contribute with images -> Please let me know.

@yashugarg sir, please allow me to do so, by assigning me the issue under the GSSOC21 label & level label.

Thank you.

**Comment by yashugarg** [comment]
Hello @DOOMSTERR 
Please do not edit the existing sections,
You can work on adding new sections though!
Thankyou

**Comment by DOOMSTERR** [comment]
Please check this PR generated and let me know if any changes are to be done.

**Comment by AdityaGarg00** [comment]
I would like to contribute I am a beginner and a part of GSSoC 21

**Comment by DOOMSTERR** [comment]
Hello sir, @yashlamba @yashugarg please let me know if any changes are to be done.

**Comment by samrudhi0909** [comment]
Can I take up this ? I am beginner , participant of GSSoC' 21.
