### ISSUE TITLE
[STYLING OF MAIN PAGE]

### ISSUE THREAD

**Issue by subhasmitapradhan** [yashlamba/simulate#177]
It's a great page but all it lacks is proper styling of home page. No matter how beautiful the content is till its not presented well then all the efforts go to vain.
Initially I want to design the whole page using UI/UX.
Then I want to use html css and js to modify how the website looks like, so that it can convey the purpose of its existance better.
It would be great if you could assign this issue to me.

**Comment by yashlamba** [comment]
Which main page are you talking about?

**Comment by subhasmitapradhan** [comment]
https://cod-ed.github.io/simulate/web/#/
This one..the link you provided in discord.

**Comment by subhasmitapradhan** [comment]
So, can I work on this?

**Comment by yashlamba** [comment]
@subhasmitapradhan, We don't use HTML CSS Javascript anywhere in our project. The main UI is designed using dart and the docs are build using the material theme of mkdocs.
