### ISSUE TITLE
Optimise Code: Separate lists of simulations.

### ISSUE THREAD

**Issue by mrmayurgithub** [yashlamba/simulate#181]
**Problem**
Currently there's a single list of simulations in the project that can be problematic while adding a new simulations, because the way the list is made is like, first few elements are of a particular simulation and other few are of another type of simulations, for example mathematics. The problem is, when we want to add a new simulation, we also have to change the list of simulations every time, shifting all the elements in a particular manner, and I think that's not good.

**Possible Solution**
A simple solution to this would be creating different lists for each type of simulation, for example if there were only two types of simulations, i.e, sorting algorithms, mathematics algorithms, then we should use two lists called sorting_simulations and maths_simulations. So that **whenever we add a new simulation we just have to add it to the end.**

**Comment by yashlamba** [comment]
Since the number of simulations is never going to exceed more than 100 and that's me be ambitious, this won't give us any significant optimization. A thing that might be worth looking into is asynchronously reading this list everywhere which you can work on if familiar with async programming in general.

**Comment by mrmayurgithub** [comment]
@yashlamba  For example, I added a sorting simulation at position 8, but the PR has not been merged. If someone else wants to add another sorting simulation, he/she will also add it at the position 8.
