### ISSUE TITLE
I want to add contributors at the bottom in read me file.

### ISSUE THREAD

**Issue by srisatya12** [yashlamba/simulate#182]
I want to add contributors at the bottom of read me  file .I'm a participant of GSSOC'21 please assign this issue to me.
LOOKS LIKE THIS :

![sc](https://user-images.githubusercontent.com/78905067/113714600-303f8800-9706-11eb-817f-5126e495176d.png)

**Comment by yashlamba** [comment]
This looks good, please go ahead. I'll suggest adding this to the README as well as the documentation. You can read more about it here: https://cod-ed.github.io/simulate/contributing/#setting-up-docs

**Comment by srisatya12** [comment]
Ok Sir will do it . @yashlamba Sir may I know the time duration cause  I have exams soon .
