### ISSUE TITLE
UI: Remove GIFS and use simple images/screenshots

### ISSUE THREAD

**Issue by yashlamba** [yashlamba/simulate#63]
Gifs are costing us smooth/efficient UI and take up a lot of space.

**Comment by yashlamba** [comment]
Update: Only sorts need to be replaced now once finalized upon the implementation

**Comment by himanshusharma89** [comment]
Hello @yashlamba , I would like to work on this issue.

**Comment by Rishabh510** [comment]
So this issue is not the priority right now. Right?
If it is then I would like to take up this issue with reference to #89 .

**Comment by yashlamba** [comment]
This is done until the implementation of sorting changes.
