### ISSUE TITLE
simulations: rose pattern: Add rose pattern Animation

### ISSUE THREAD

**Issue by yashlamba** [yashlamba/simulate#71]
Animate Rose Pattern like Lissajous Curve simulation, see #70

**Comment by rohg007** [comment]
Can I try this out

**Comment by nicks101** [comment]
There are no assignees on this one. Can I work on this issue?

**Comment by yashlamba** [comment]
Sure, go ahead and let me know if you need any help! If participating under GSSoC, let us know when you make progress and we'll check out your branch. Don't open a PR before discussing it.

**Comment by payal-98** [comment]
If somebody is not working...Can I work on this issue?
