### ISSUE TITLE
simulation: Epicycloids as envelope of pencil of lines

### ISSUE THREAD

**Issue by sakshamarora1** [yashlamba/simulate#75]
**Epicycloid curves as envelope of pencil of lines**

**Category Proposed:** Mathematics

**Additional points/links:**
- https://en.wikipedia.org/wiki/Epicycloid

Assigned ID: 6

**Comment by yashlamba** [comment]
To my understanding, there are multiple ways we can have epicycloid curves drawn. Let's make this a little specific. Name of simulation needs to change.
