### ISSUE TITLE
pubspec: update pubspec.yaml with latest versions of packages

### ISSUE THREAD

**Issue by yashlamba** [yashlamba/simulate#85]
We haven't mentioned any minimum versions in the packages which isn't really a good practice, let's update it.

**Comment by himanshusharma89** [comment]
Hey @yashlamba , I would like to work on this issue. I have already set up the application in my PC.

**Comment by Rishabh510** [comment]
I would like to take up this issue.

**Comment by Rishabh510** [comment]
> I would like to take up this issue.

Also, if we leave the packages without defining their versions, our IDE automatically takes the latest version of the package and updates our app according to that. Hence, maybe we can leave pubspec.yaml file as it is.

**Comment by yashlamba** [comment]
Hi @Rishabh510, @himanshusharma89 fixed this in #86. I know that recent versions are fetched but this helps us keep track of migrations like we forgot with provider causing errors in installation #84.

**Comment by yashlamba** [comment]
Via #86
