### ISSUE TITLE
lib: src: simulations: fourier_series pixels overflow 

### ISSUE THREAD

**Issue by Rishabh510** [yashlamba/simulate#87]
Fourier series simulation has overflowing pixels in large screen devices.

Screenshot of BUG (top right of image)
![Screenshot_20200301-002751](https://user-images.githubusercontent.com/42823059/75613576-48cd8e00-5b55-11ea-8de6-d0c3746fa6bd.jpg)

Device: Asus max pro m1
 - OS:: Android
 - Screen Width 440px

**Additional context**
I would like to up this **issue**.

**Comment by yashlamba** [comment]
This has been on my radar, thanks for opening an issue. You can work on this and ping me if you need help.

**Comment by yashlamba** [comment]
Checked just now, I don't think this issue persists anymore.
