### ISSUE TITLE
lib: src: Bubble sort dark mode gif inverted

### ISSUE THREAD

**Issue by Rishabh510** [yashlamba/simulate#89]
Bubble sort gif works perfectly fine in light mode but camouflages with the background in dark mode. 

**To Reproduce**
1. Turn on dark mode
2. Bubble Sort bars camouflage with black background.

**Expected behavior**
The gif should be inverted in dark mode.

**Screenshots**
![Screenshot_20200301-002631](https://user-images.githubusercontent.com/42823059/75613709-e70e2380-5b56-11ea-8c19-4df5f22ce50b.jpg)
![Screenshot_20200301-002640](https://user-images.githubusercontent.com/42823059/75613710-e7a6ba00-5b56-11ea-830c-5979832f1746.jpg)

 - Device: Asus max pro m1
 - OS: Android
 - Screen Width: 440px

**Additional context**
I would like to work on this **issue**.

**Comment by yashlamba** [comment]
Ah, the thing is because sort implementation is yet not finalized yet, I haven't updated this sort gifs and they'll probably be remove once the are finalized. Check #63.
