### ISSUE TITLE
simulation: STAR FIELD

### ISSUE THREAD

**Issue by kmrakash** [yashlamba/simulate#90]
**Proposed Simulation Name**
Brief description of the simulation

**Category Proposed:** Physics

**Additional points/links:**
Links and points
https://youtu.be/17WoOqgXsRM

**Comment by kamal-kaur04** [comment]
Hii @kmrakash, May I know what to be done in this issue?

**Comment by kmrakash** [comment]
@yashlamba  should i work on this part now ??

**Comment by yashlamba** [comment]
Starfield isn't a categorizable simulation. I don't think it is something we need in simulate.
