### ISSUE TITLE
simulation: Maurer's Rose simulation

### ISSUE THREAD

**Issue by yashlamba** [yashlamba/simulate#93]
**Maurer's Rose**
A Maurer rose consists of some lines that connect some points on a rose curve.

**Category Proposed:** Mathematics

**Additional points/links:**
https://en.wikipedia.org/wiki/Maurer_rose

**Comment by dwvicy** [comment]
I'd like to try this out with some help.

**Comment by kmrakash** [comment]
Please Check PR # 102 
I have completed this pattern
